modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''
logoFile="assets/blockvariantswapper/icon.png"

# Mixin configs for the mod. Applied on both physical sides; the client config only
# contains client-only mixins and is guarded by the "client" side flag inside the JSON.
[[mixins]]
config="blockvariantswapper.mixins.json"

[[mixins]]
config="blockvariantswapper.client.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
